# Generated by Django 4.0.4 on 2022-05-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbin', '0002_alter_smartbin_bin_id_alter_smartbin_fil_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartbin',
            old_name='fil_status',
            new_name='fill_status',
        ),
    ]
