# Generated by Django 4.0.4 on 2022-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CU', 'Customer'), ('CA', 'Collection Agent'), ('MU', 'Municipality'), ('AD', 'Admin')], default='AD', max_length=2),
        ),
    ]
