# Generated by Django 4.0.4 on 2022-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CU', 'Customer'), ('CA', 'Collection Agent'), ('MU', 'Municipality'), ('AD', 'Admin'), ('RE', 'Recycler')], default='AD', max_length=2),
        ),
    ]
