# Generated by Django 4.0.4 on 2022-05-30 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartbin', '0002_alter_smartbin_bin_id_alter_smartbin_fil_status'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ASSIGNED '), ('C', 'COLLECTED')], max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Collection_date', models.DateTimeField(null=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartbin.smartbin')),
                ('collection_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.collectionagent')),
            ],
        ),
    ]
