# Generated by Django 4.0.4 on 2022-05-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_collection_date_booking_collection_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bin',
            new_name='smartbin',
        ),
    ]
