# Generated by Django 4.0.4 on 2022-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_collection_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned '), ('Collected', 'Collected'), ('Verified', 'Verified')], max_length=10),
        ),
    ]
