# Generated by Django 4.0.4 on 2022-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=10),
        ),
    ]
