# Generated by Django 4.0.4 on 2022-05-29 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
