# Generated by Django 4.0.4 on 2022-06-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recycleramount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recycleramount',
            old_name='iron_amount',
            new_name='metal_amount',
        ),
    ]
